/**
 * AUTO-GENERATED by generate-tracks.js
 * Do not edit by hand — just re-run the script after adding/removing files.
 * Generated: 2026-08-06T18:15:02.770Z
 *
 * This file is completely rewritten every run, so deleted songs disappear automatically.
 */
window.TRACKS_DATA = {
  "ancient": {
    "name": "Ancient",
    "icon": "🏛",
    "description": "Mysterious, epic, foundational vibes",
    "songs": [
      {
        "title": "[boymanthemale] JoJo Battle Tendency OST： Ancientry (wYO02RCDJ1E)",
        "artist": "",
        "file": "audio/ancient/[boymanthemale] JoJo Battle Tendency OST： Ancientry (wYO02RCDJ1E).mp3",
        "duration": null
      },
      {
        "title": "[Compendium] Luffy Reborn ONE PIECE GEAR5 Original Soundtrack (CjO6kQmgQCc)",
        "artist": "",
        "file": "audio/ancient/[Compendium] Luffy Reborn - ONE PIECE GEAR5 Original Soundtrack (CjO6kQmgQCc).mp3",
        "duration": null
      },
      {
        "title": "[Diego Mitre Music] Imu's Theme ｜ Destruction of Lulusia Kingdom ｜ One Piece 1089 ｜ OST Cover (JDj1QHxMs6o)",
        "artist": "",
        "file": "audio/ancient/[Diego Mitre Music] Imu's Theme ｜ Destruction of Lulusia Kingdom ｜ One Piece 1089 ｜ OST Cover (JDj1QHxMs6o).mp3",
        "duration": null
      },
      {
        "title": "[Joseph Hacker] Voices Of The Void Main Theme (TRdidwwGyes)",
        "artist": "",
        "file": "audio/ancient/[Joseph Hacker] Voices Of The Void - Main Theme (TRdidwwGyes).mp3",
        "duration": null
      },
      {
        "title": "[Koyamie] One Piece OST • WANOKUNI • Kozuki Family's Theme ~~Downfall~~ (FsPZ t2CFmU)",
        "artist": "",
        "file": "audio/ancient/[Koyamie] One Piece OST • WANOKUNI • Kozuki Family's Theme ~~Downfall~~ (FsPZ-t2CFmU).mp3",
        "duration": null
      },
      {
        "title": "[Koyamie] One Piece OST • WANOKUNI • Kurozumi Orochi's Theme (ww69i7bEj6g)",
        "artist": "",
        "file": "audio/ancient/[Koyamie] One Piece OST • WANOKUNI • Kurozumi Orochi's Theme (ww69i7bEj6g).mp3",
        "duration": null
      },
      {
        "title": "[Koyamie] One Piece OST • WANOKUNI • Oden's Tatami Room Tune instrumental (LLnU EZtDtI)",
        "artist": "",
        "file": "audio/ancient/[Koyamie] One Piece OST • WANOKUNI • Oden's Tatami Room Tune instrumental (LLnU_EZtDtI).mp3",
        "duration": null
      },
      {
        "title": "[Osirois Music Topic] A Strange Moonlit Night (XOfNyJBrqS4)",
        "artist": "",
        "file": "audio/ancient/[Osirois Music - Topic] A Strange Moonlit Night (XOfNyJBrqS4).mp3",
        "duration": null
      },
      {
        "title": "[Osirois Music Topic] Scarlet Forest (13XSvphdmo4)",
        "artist": "",
        "file": "audio/ancient/[Osirois Music - Topic] Scarlet Forest (13XSvphdmo4).mp3",
        "duration": null
      },
      {
        "title": "[Suki] JJBA Dark Rebirth (Theme of DIO) ( Qq1B5na s)",
        "artist": "",
        "file": "audio/ancient/[Suki] JJBA - Dark Rebirth (Theme of DIO) (_Qq1B5na--s).mp3",
        "duration": null
      },
      {
        "title": "[Taku Iwasaki Topic] awake ( W8MBjTk2E8)",
        "artist": "",
        "file": "audio/ancient/[Taku Iwasaki - Topic] awake (-W8MBjTk2E8).mp3",
        "duration": null
      },
      {
        "title": "[The Puppet Master] FNAF 2： Main Menu Theme (bJZ 0jRapvU)",
        "artist": "",
        "file": "audio/ancient/[The Puppet Master] FNAF 2： Main Menu Theme (bJZ_0jRapvU).mp3",
        "duration": null
      }
    ]
  },
  "classical": {
    "name": "Classical",
    "icon": "🏺",
    "description": "Grandeur and rising empires",
    "songs": [
      {
        "title": "[AD bị tha hóa] Yume Nikki Ending song (s9pEbOJ7NaM)",
        "artist": "",
        "file": "audio/classical/[AD bị tha hóa] Yume Nikki Ending song (s9pEbOJ7NaM).mp3",
        "duration": null
      },
      {
        "title": "[Arubus Hollow] FNaF 3 Good Ending Song ˝Don't Go˝ (c4IDX7cloWk)",
        "artist": "",
        "file": "audio/classical/[Arubus Hollow] FNaF 3 Good Ending Song ˝Don't Go˝ (c4IDX7cloWk).mp3",
        "duration": null
      },
      {
        "title": "[Batter Montague (The Batter)] Yume Nikki Barracks Settlement (DypG0349cUU)",
        "artist": "",
        "file": "audio/classical/[Batter Montague (The Batter)] Yume Nikki - Barracks Settlement (DypG0349cUU).mp3",
        "duration": null
      },
      {
        "title": "[Giorno Yoshikage] Golden Wind OST Vol.3 Diavolo Theme (NN2TOdiPtG4)",
        "artist": "",
        "file": "audio/classical/[Giorno Yoshikage] Golden Wind OST Vol.3 - Diavolo Theme (NN2TOdiPtG4).mp3",
        "duration": null
      },
      {
        "title": "[gmodfan11] Sister Location Soundtrack The Forbidden Nocturne (Custom Night 3) (5qKIehhuXaI)",
        "artist": "",
        "file": "audio/classical/[gmodfan11] Sister Location Soundtrack - The Forbidden Nocturne (Custom Night 3) (5qKIehhuXaI).mp3",
        "duration": null
      },
      {
        "title": "[Greytezi] ˝Nowhere to Run˝ FNaF 6 OST (xhspICxdqqE)",
        "artist": "",
        "file": "audio/classical/[Greytezi] ˝Nowhere to Run˝ - FNaF 6 OST (xhspICxdqqE).mp3",
        "duration": null
      },
      {
        "title": "[Koyamie] One Piece OST • WANOKUNI • Ebisu Town's Theme (jYH65Fsmgc4)",
        "artist": "",
        "file": "audio/classical/[Koyamie] One Piece OST • WANOKUNI • Ebisu Town's Theme (jYH65Fsmgc4).mp3",
        "duration": null
      },
      {
        "title": "[Koyamie] One Piece OST • WANOKUNI • Fun Daily Life ~Wano Country Arc~ (ief0Ph2UnoY)",
        "artist": "",
        "file": "audio/classical/[Koyamie] One Piece OST • WANOKUNI • Fun Daily Life ~Wano Country Arc~ (ief0Ph2UnoY).mp3",
        "duration": null
      },
      {
        "title": "[Toby Fox Topic] Hip Shop (D83BxptHcRc)",
        "artist": "",
        "file": "audio/classical/[Toby Fox - Topic] Hip Shop (D83BxptHcRc).mp3",
        "duration": null
      },
      {
        "title": "[Toby Fox Topic] My Castle Town (Bl YMD6yePc)",
        "artist": "",
        "file": "audio/classical/[Toby Fox - Topic] My Castle Town (Bl-YMD6yePc).mp3",
        "duration": null
      },
      {
        "title": "[wd0] Fullmetal Alchemist Brotherhood OST Lapis Philosophorum (Q 439qLQzHs)",
        "artist": "",
        "file": "audio/classical/[wd0] Fullmetal Alchemist Brotherhood OST - Lapis Philosophorum (Q_439qLQzHs).mp3",
        "duration": null
      },
      {
        "title": "[wd0] Fullmetal Alchemist Brotherhood OST 3 Sorrowful Stone (nCt4aLirnrk)",
        "artist": "",
        "file": "audio/classical/[wd0] Fullmetal Alchemist Brotherhood OST 3 - Sorrowful Stone (nCt4aLirnrk).mp3",
        "duration": null
      }
    ]
  },
  "medieval": {
    "name": "Medieval",
    "icon": "🏰",
    "description": "Castles, faith, and steel",
    "songs": [
      {
        "title": "[Adon Trowbridge (PFL123)] Five Nights At Freddy's 3 Full Trailer Theme (3k3dmMSZnxQ)",
        "artist": "",
        "file": "audio/medieval/[Adon Trowbridge (PFL123)] Five Nights At Freddy's 3 - Full Trailer Theme (3k3dmMSZnxQ).mp3",
        "duration": null
      },
      {
        "title": "[batta Topic] chase ～Acoustic Ver.～ (ZDRKubdmIk8)",
        "artist": "",
        "file": "audio/medieval/[batta - Topic] chase ～Acoustic Ver.～ (ZDRKubdmIk8).mp3",
        "duration": null
      },
      {
        "title": "[Drayken] Re：Zero kara Hajimeru Isekai Seikatsu Episode 15 ED OST ( vzlO4yvHVk)",
        "artist": "",
        "file": "audio/medieval/[Drayken] Re：Zero kara Hajimeru Isekai Seikatsu - Episode 15 ED OST (_vzlO4yvHVk).mp3",
        "duration": null
      },
      {
        "title": "[Hgfyff gear] FNAF SISTER LOCATION Venta Black (HQ) (yiHfvsUsj5c)",
        "artist": "",
        "file": "audio/medieval/[Hgfyff gear] FNAF SISTER LOCATION - Venta Black (HQ) (yiHfvsUsj5c).mp3",
        "duration": null
      },
      {
        "title": "[InkySync] Yume Nikki OST Saving Theme (1EOo4YtKKjA)",
        "artist": "",
        "file": "audio/medieval/[InkySync] Yume Nikki OST - Saving Theme (1EOo4YtKKjA).mp3",
        "duration": null
      },
      {
        "title": "[Jinouga] Undertale OST Bergentrückung + ASGORE [Fixed loop] (96YaOyAAXAg)",
        "artist": "",
        "file": "audio/medieval/[Jinouga] Undertale OST - Bergentrückung + ASGORE [Fixed loop] (96YaOyAAXAg).mp3",
        "duration": null
      },
      {
        "title": "[Koyamie] One Piece OST • WANOKUNI • Go~! My Servant~ Big Mom!! (5e5cYwDtUCo)",
        "artist": "",
        "file": "audio/medieval/[Koyamie] One Piece OST • WANOKUNI • Go~! My Servant~ Big Mom!! (5e5cYwDtUCo).mp3",
        "duration": null
      },
      {
        "title": "[Koyamie] One Piece OST • WANOKUNI • Wano Country Opening Curtains, Closing Curtains Theme (I6iRG 6nG9A)",
        "artist": "",
        "file": "audio/medieval/[Koyamie] One Piece OST • WANOKUNI • Wano Country - Opening Curtains, Closing Curtains Theme (I6iRG-6nG9A).mp3",
        "duration": null
      },
      {
        "title": "[M8TNL] FNAF： Help Wanted 2 OST Scorched Cranberries Special (Credits) (GBnH2kDtRZM)",
        "artist": "",
        "file": "audio/medieval/[M8TNL] FNAF： Help Wanted 2 OST - Scorched Cranberries Special (Credits) (GBnH2kDtRZM).mp3",
        "duration": null
      },
      {
        "title": "[Michael Wyckoff] Michael Wyckoff & Jonathan LaMarche Little Tuscany (Boneworks OST) (wWkoZbVEOeI)",
        "artist": "",
        "file": "audio/medieval/[Michael Wyckoff] Michael Wyckoff & Jonathan LaMarche - Little Tuscany (Boneworks OST) (wWkoZbVEOeI).mp3",
        "duration": null
      },
      {
        "title": "[Mouks] FNAF Secret of the Mimic OST： A Poisonous Kiss (Credits) (YU5WuyQeEuw)",
        "artist": "",
        "file": "audio/medieval/[Mouks] FNAF Secret of the Mimic OST： A Poisonous Kiss (Credits) (YU5WuyQeEuw).mp3",
        "duration": null
      },
      {
        "title": "[Mouks] FNAF Secret of the Mimic OST： Tragedy and Comedy (BigTop Showroom) (scjZ45ypHDA)",
        "artist": "",
        "file": "audio/medieval/[Mouks] FNAF Secret of the Mimic OST： Tragedy and Comedy (BigTop Showroom) (scjZ45ypHDA).mp3",
        "duration": null
      },
      {
        "title": "[out1190] Last Train Home (oG7jKUHsLfY)",
        "artist": "",
        "file": "audio/medieval/[out1190] Last Train Home (oG7jKUHsLfY).mp3",
        "duration": null
      },
      {
        "title": "[Shiro Sagisu Topic] I. SHINJI (8S2qkmO1irk)",
        "artist": "",
        "file": "audio/medieval/[Shiro Sagisu - Topic] I. SHINJI (8S2qkmO1irk).mp3",
        "duration": null
      },
      {
        "title": "[澤野弘之 ／ SawanoHiroyuki[nZk]] Vogel im Käfig (H76 uW1Fnso)",
        "artist": "",
        "file": "audio/medieval/[澤野弘之 ／ SawanoHiroyuki[nZk]] Vogel im Käfig (H76_uW1Fnso).mp3",
        "duration": null
      },
      {
        "title": "Dark Sanctuary [QQQq1T06lYg]",
        "artist": "",
        "file": "audio/medieval/Dark Sanctuary [QQQq1T06lYg].mp3",
        "duration": null
      }
    ]
  },
  "renaissance": {
    "name": "Renaissance",
    "icon": "🎨",
    "description": "Discovery and enlightenment",
    "songs": [
      {
        "title": "[AwardsProduction] One Piece opening 5 HD 1080p (RO VGv4GT9k)",
        "artist": "",
        "file": "audio/renaissance/[AwardsProduction] One Piece opening 5 HD 1080p (RO_VGv4GT9k).mp3",
        "duration": null
      },
      {
        "title": "[gabriel15xD] Killer (Yoshikage Kira's Theme) Jojo's Bizarre Adventure Part 4： Diamond Is Unbreakable (9yGGNohmAT0)",
        "artist": "",
        "file": "audio/renaissance/[gabriel15xD] Killer (Yoshikage Kira's Theme) - Jojo's Bizarre Adventure Part 4： Diamond Is Unbreakable (9yGGNohmAT0).mp3",
        "duration": null
      },
      {
        "title": "[GPM 3] Jojo's Bizarre Adventure ： Stone Ocean ｜ ED 1 ˝Distant Dreamer˝ (ejRgi6YAh54)",
        "artist": "",
        "file": "audio/renaissance/[GPM 3] Jojo's Bizarre Adventure ： Stone Ocean ｜ ED 1  - ˝Distant Dreamer˝ (ejRgi6YAh54).mp3",
        "duration": null
      },
      {
        "title": "[Luffys1girl] Chopper／Luffy Dr. Tony Tony Chopper (4629Lzrkyds)",
        "artist": "",
        "file": "audio/renaissance/[Luffys1girl] Chopper／Luffy - Dr. Tony Tony Chopper (4629Lzrkyds).mp3",
        "duration": null
      },
      {
        "title": "[Michael Wyckoff] Michael Wyckoff Stargrid (Bonelab OST) (pZJvBXU2trM)",
        "artist": "",
        "file": "audio/renaissance/[Michael Wyckoff] Michael Wyckoff - Stargrid (Bonelab OST) (pZJvBXU2trM).mp3",
        "duration": null
      },
      {
        "title": "[ONE PIECE Official YouTube Channel] ＜エンディングテーマ映像フル＞TVアニメ「ONE PIECE」／「Raise」歌：Chilli Beans. (stXbvYGvrxA)",
        "artist": "",
        "file": "audio/renaissance/[ONE PIECE Official YouTube Channel] ＜エンディングテーマ映像フル＞TVアニメ「ONE PIECE」／「Raise」歌：Chilli Beans. (stXbvYGvrxA).mp3",
        "duration": null
      },
      {
        "title": "[One Piece RoronoaZoro] Song Soul Pocus[ONE PIECE] (xX2t JZuuYw)",
        "artist": "",
        "file": "audio/renaissance/[One Piece RoronoaZoro] Song Soul Pocus[ONE PIECE] (xX2t_JZuuYw).mp3",
        "duration": null
      },
      {
        "title": "[Toby Fox Topic] My Castle Town (Bl YMD6yePc)",
        "artist": "",
        "file": "audio/renaissance/[Toby Fox - Topic] My Castle Town (Bl-YMD6yePc).mp3",
        "duration": null
      },
      {
        "title": "[Toei Animation] One Piece ｜ New Opening Theme ｜ The Peak SEKAI NO OWARI (LrCmsOAgvxk)",
        "artist": "",
        "file": "audio/renaissance/[Toei Animation] One Piece ｜ New Opening Theme ｜ The Peak - SEKAI NO OWARI (LrCmsOAgvxk).mp3",
        "duration": null
      },
      {
        "title": "[vidgam] Neon Genesis Evangelion — FLY ME TO THE MOON — CLAIRE (ED Ending Full NGE OST Soundtrack Lyrics) (Ixi0sUpLVRc)",
        "artist": "",
        "file": "audio/renaissance/[vidgam] Neon Genesis Evangelion — FLY ME TO THE MOON — CLAIRE (ED Ending Full NGE OST Soundtrack Lyrics) (Ixi0sUpLVRc).mp3",
        "duration": null
      },
      {
        "title": "[wd0] Fullmetal Alchemist Brotherhood OST Main Theme (SkNjCfMjRXA)",
        "artist": "",
        "file": "audio/renaissance/[wd0] Fullmetal Alchemist Brotherhood OST - Main Theme (SkNjCfMjRXA).mp3",
        "duration": null
      },
      {
        "title": "[wd0] Fullmetal Alchemist Brotherhood OST 2 The Fullmetal Alchemist (evjJ z N ig)",
        "artist": "",
        "file": "audio/renaissance/[wd0] Fullmetal Alchemist Brotherhood OST 2 - The Fullmetal Alchemist (evjJ-z_N-ig).mp3",
        "duration": null
      },
      {
        "title": "[XImmortalX] One Piece ST New World Symphony (TL8KazzwdAU)",
        "artist": "",
        "file": "audio/renaissance/[XImmortalX] One Piece ST - New World Symphony (TL8KazzwdAU).mp3",
        "duration": null
      },
      {
        "title": "[Yugo Kanno Topic] Clock Works (3JA 7JRuLso)",
        "artist": "",
        "file": "audio/renaissance/[Yugo Kanno - Topic] Clock Works (3JA-7JRuLso).mp3",
        "duration": null
      },
      {
        "title": "[Zoro OST] One Piece Great Scenes OST Soul Pocus ~Song of the Queen~ Full Song with Lyrics (Episode 877) (FufD0aCVUec)",
        "artist": "",
        "file": "audio/renaissance/[Zoro OST] One Piece Great Scenes OST - Soul Pocus ~Song of the Queen~ - Full Song with Lyrics (Episode 877) (FufD0aCVUec).mp3",
        "duration": null
      },
      {
        "title": "[ハセガワダイスケ Daisuke Hasegawa Official YouTube Channel] 裏切り者のレクイエム (x06wB8UDxMI)",
        "artist": "",
        "file": "audio/renaissance/[ハセガワダイスケ Daisuke Hasegawa Official YouTube Channel] 裏切り者のレクイエム (x06wB8UDxMI).mp3",
        "duration": null
      }
    ]
  },
  "industrial": {
    "name": "Industrial",
    "icon": "⚙",
    "description": "Factories, steam, and progress",
    "songs": [
      {
        "title": "[[CK9C] ChaoticCanineCulture] FNAF SISTER LOCATION SONG ｜ ˝Funtime Dance Floor˝ by CK9C [Official SFM] (Cw6FZzQQNa8)",
        "artist": "",
        "file": "audio/industrial/[[CK9C] ChaoticCanineCulture] FNAF SISTER LOCATION SONG ｜ ˝Funtime Dance Floor˝ by CK9C [Official SFM] (Cw6FZzQQNa8).mp3",
        "duration": null
      },
      {
        "title": "[[CK9C] ChaoticCanineCulture] FNAF SISTER LOCATION SONG ｜ ˝They'll Keep You Running˝ by CK9C [Official SFM] (EMLwtpuccLM)",
        "artist": "",
        "file": "audio/industrial/[[CK9C] ChaoticCanineCulture] FNAF SISTER LOCATION SONG ｜ ˝They'll Keep You Running˝ by CK9C [Official SFM] (EMLwtpuccLM).mp3",
        "duration": null
      },
      {
        "title": "[[CK9C] ChaoticCanineCulture] FNAF SISTER LOCATION SONG ｜ ˝Trust Me˝ by CK9C [Official SFM] (DpPsVs8be U)",
        "artist": "",
        "file": "audio/industrial/[[CK9C] ChaoticCanineCulture] FNAF SISTER LOCATION SONG ｜ ˝Trust Me˝ by CK9C [Official SFM] (DpPsVs8be-U).mp3",
        "duration": null
      },
      {
        "title": "[[CK9C] ChaoticCanineCulture] FNAF SISTER LOCATION SONG ｜ ˝You Can't Hide˝ by CK9C [Official SFM] (C2fihvzCJ3A)",
        "artist": "",
        "file": "audio/industrial/[[CK9C] ChaoticCanineCulture] FNAF SISTER LOCATION SONG ｜ ˝You Can't Hide˝ by CK9C [Official SFM] (C2fihvzCJ3A).mp3",
        "duration": null
      },
      {
        "title": "[animelab] One Punch Man Official Opening The Hero!! Set Fire to the Furious Fist (atxYe nOa9w)",
        "artist": "",
        "file": "audio/industrial/[animelab] One Punch Man - Official Opening - The Hero!! Set Fire to the Furious Fist (atxYe-nOa9w).mp3",
        "duration": null
      },
      {
        "title": "[AnimeScene Wesh] JoJo's Bizarre Adventure： Diamond is Unbreakable Opening 1v2 (Dubstep Version HD) (FBULQErzDB8)",
        "artist": "",
        "file": "audio/industrial/[AnimeScene Wesh] JoJo's Bizarre Adventure： Diamond is Unbreakable Opening 1v2 (Dubstep Version HD) (FBULQErzDB8).mp3",
        "duration": null
      },
      {
        "title": "[Animeあの TV] JoJo's Bizarre Adventure Opening 3 STAND PROUD (dOQWNEv4 6U)",
        "artist": "",
        "file": "audio/industrial/[Animeあの TV] JoJo's Bizarre Adventure Opening 3 STAND PROUD (dOQWNEv4_6U).mp3",
        "duration": null
      },
      {
        "title": "[epicsurfingvids] FNaF： Sister Location Title Screen ｜ SL Menu Music ｜ Five Nights at Freddy's (rCmnlSFFw 4)",
        "artist": "",
        "file": "audio/industrial/[epicsurfingvids] FNaF： Sister Location Title Screen ｜ SL Menu Music ｜ Five Nights at Freddy's (rCmnlSFFw-4).mp3",
        "duration": null
      },
      {
        "title": "[Glamrockzie] DJ Music Man Boss Fight Theme／Song CLEAN AUDIO + NO CUTS (OST) [FNAF SB] (IQT4naAv1Us)",
        "artist": "",
        "file": "audio/industrial/[Glamrockzie] DJ Music Man Boss Fight Theme／Song - CLEAN AUDIO + NO CUTS (OST) - [FNAF SB] (IQT4naAv1Us).mp3",
        "duration": null
      },
      {
        "title": "[Jaze Cinema] FNAF Song： ˝I Got No Time˝ by The Living Tombstone (CG5 Remix) (4FDHdWYWTzY)",
        "artist": "",
        "file": "audio/industrial/[Jaze Cinema] FNAF Song： ˝I Got No Time˝ by The Living Tombstone (CG5 Remix) (4FDHdWYWTzY).mp3",
        "duration": null
      },
      {
        "title": "[JT Music] Five Long Nights (eZ0ip0tUCz8)",
        "artist": "",
        "file": "audio/industrial/[JT Music] Five Long Nights (eZ0ip0tUCz8).mp3",
        "duration": null
      },
      {
        "title": "[JT Music] Five More Nights (446U9P8BHMc)",
        "artist": "",
        "file": "audio/industrial/[JT Music] Five More Nights (446U9P8BHMc).mp3",
        "duration": null
      },
      {
        "title": "[JT Music] You Belong Here (3lAKOX9zg5g)",
        "artist": "",
        "file": "audio/industrial/[JT Music] You Belong Here (3lAKOX9zg5g).mp3",
        "duration": null
      },
      {
        "title": "[Mouks] FNAF Secret of the Mimic OST： Bitter Sweet Sedation (Doll Hospital) (SorR3ZOQH3I)",
        "artist": "",
        "file": "audio/industrial/[Mouks] FNAF Secret of the Mimic OST： Bitter Sweet Sedation (Doll Hospital) (SorR3ZOQH3I).mp3",
        "duration": null
      },
      {
        "title": "[Mouks] FNAF Secret of the Mimic OST： Dark Roast Triple Shot Extravaganza (d6ZI1x2Ovus)",
        "artist": "",
        "file": "audio/industrial/[Mouks] FNAF Secret of the Mimic OST： Dark Roast Triple Shot Extravaganza (d6ZI1x2Ovus).mp3",
        "duration": null
      },
      {
        "title": "[Mouks] FNAF Security Breach OST： Snap! Goes The SFinal Chord (Venta Black Remix) (Unused) (IdO73dsjldo)",
        "artist": "",
        "file": "audio/industrial/[Mouks] FNAF Security Breach OST： Snap! Goes The SFinal Chord (Venta Black Remix) (Unused) (IdO73dsjldo).mp3",
        "duration": null
      },
      {
        "title": "[ReAsto] Fullmetal Alchemist Brotherhood OP 1 (XCsppc963NI)",
        "artist": "",
        "file": "audio/industrial/[ReAsto] Fullmetal Alchemist Brotherhood OP 1 (XCsppc963NI).mp3",
        "duration": null
      },
      {
        "title": "[Rooster Time] FNAF Song： ˝Below The Surface˝ (DHeusta Remix) (nm9kVqJAudo)",
        "artist": "",
        "file": "audio/industrial/[Rooster Time] FNAF Song： ˝Below The Surface˝ (DHeusta Remix) (nm9kVqJAudo).mp3",
        "duration": null
      },
      {
        "title": "[Zen] JoJo's Bizarre Adventure ： Phantom Blood Opening 1 HD Creditless『Sono Chi No Sadame』 (1ZKAQzGYYSo)",
        "artist": "",
        "file": "audio/industrial/[Zen] JoJo's Bizarre Adventure ： Phantom Blood - Opening 1 HD Creditless『Sono Chi No Sadame』 (1ZKAQzGYYSo).mp3",
        "duration": null
      },
      {
        "title": "Dance with STEEL BALL RUN [AFZFhMyiSZ8]",
        "artist": "",
        "file": "audio/industrial/Dance with STEEL BALL RUN [AFZFhMyiSZ8].mp3",
        "duration": null
      },
      {
        "title": "ətˈæk 0N tάɪtn [zroFzv7sFis]",
        "artist": "",
        "file": "audio/industrial/ətˈæk 0N tάɪtn [zroFzv7sFis].mp3",
        "duration": null
      },
      {
        "title": "僕の戦争 [gYuO6OUm6SQ]",
        "artist": "",
        "file": "audio/industrial/僕の戦争 [gYuO6OUm6SQ].mp3",
        "duration": null
      },
      {
        "title": "神聖かまってちゃん 夕暮れの鳥／Shinsei Kamattechan Yuugure no tori [sUW4dDWiz A]",
        "artist": "",
        "file": "audio/industrial/神聖かまってちゃん-夕暮れの鳥／Shinsei Kamattechan-Yuugure no tori [sUW4dDWiz-A].mp3",
        "duration": null
      }
    ]
  },
  "modern": {
    "name": "Modern",
    "icon": "✈",
    "description": "World wars to the jet age — high energy",
    "songs": [
      {
        "title": "[Black Gryph0n] STUCK INSIDE FNAF MUSIC VIDEO (Living Tombstone, CG5, Black Gryph0n, Baasik, Kevin Foster) (AWPB2p1CEZQ)",
        "artist": "",
        "file": "audio/modern/[Black Gryph0n] STUCK INSIDE - FNAF MUSIC VIDEO (Living Tombstone, CG5, Black Gryph0n, Baasik, Kevin Foster) (AWPB2p1CEZQ).mp3",
        "duration": null
      },
      {
        "title": "[BonBun Films] [SFM FNAF] STAY CALM FNaF Song by Griffinilla (2018 REMAKE) (fUSJxnRzTQY)",
        "artist": "",
        "file": "audio/modern/[BonBun Films] [SFM FNAF] STAY CALM - FNaF Song by Griffinilla (2018 REMAKE) (fUSJxnRzTQY).mp3",
        "duration": null
      },
      {
        "title": "[CG5] FNAF 6 SONG ▶ ˝Labyrinth˝ ｜ CG5 (O2o5HtgKIhk)",
        "artist": "",
        "file": "audio/modern/[CG5] FNAF 6 SONG ▶ ˝Labyrinth˝ ｜ CG5 (O2o5HtgKIhk).mp3",
        "duration": null
      },
      {
        "title": "[Crunchyroll] Attack on Titan Opening 1 ｜ Feuerroter Pfeil und Bogen (8OkpRK2 gVs)",
        "artist": "",
        "file": "audio/modern/[Crunchyroll] Attack on Titan Opening 1 ｜ Feuerroter Pfeil und Bogen (8OkpRK2_gVs).mp3",
        "duration": null
      },
      {
        "title": "[DAGames] FNAF SISTER LOCATION SONG (LEFT BEHIND) DAGames (tE aSvBn0I)",
        "artist": "",
        "file": "audio/modern/[DAGames] FNAF SISTER LOCATION SONG (LEFT BEHIND) - DAGames (tE--aSvBn0I).mp3",
        "duration": null
      },
      {
        "title": "[executive] FNAF Help Wanted 2 OST： Doomsday Ride (Carousel) (mgRuBT8dll4)",
        "artist": "",
        "file": "audio/modern/[executive] FNAF Help Wanted 2 OST： Doomsday Ride (Carousel) (mgRuBT8dll4).mp3",
        "duration": null
      },
      {
        "title": "[Lakeshore Records] CYBERPUNK 2077 SOUNDTRACK I REALLY WANT TO STAY AT YOUR HOUSE by Rosa Walton & Hallie Coggins (gzbLODUb1sA)",
        "artist": "",
        "file": "audio/modern/[Lakeshore Records] CYBERPUNK 2077 SOUNDTRACK - I REALLY WANT TO STAY AT YOUR HOUSE by Rosa Walton & Hallie Coggins (gzbLODUb1sA).mp3",
        "duration": null
      },
      {
        "title": "[Lakeshore Records] CYBERPUNK 2077 SOUNDTRACK WHO'S READY FOR TOMORROW by Rat Boy & IBDY (Official Video) (jLXTBbMRxK8)",
        "artist": "",
        "file": "audio/modern/[Lakeshore Records] CYBERPUNK 2077 SOUNDTRACK - WHO'S READY FOR TOMORROW by Rat Boy & IBDY (Official Video) (jLXTBbMRxK8).mp3",
        "duration": null
      },
      {
        "title": "[Literally Stuart] Markiplier Edge Of Sleep Intro (r91zxMFxeM8)",
        "artist": "",
        "file": "audio/modern/[Literally Stuart] Markiplier Edge Of Sleep Intro (r91zxMFxeM8).mp3",
        "duration": null
      },
      {
        "title": "[Lunar Studios] [FNAF SFM] Animatronic Prototype (6EcPE3AQM7w)",
        "artist": "",
        "file": "audio/modern/[Lunar Studios] [FNAF SFM] Animatronic Prototype (6EcPE3AQM7w).mp3",
        "duration": null
      },
      {
        "title": "[Michael Wyckoff] Michael Wyckoff House of Monogon (Boneworks OST) (lyq sEF8iCQ)",
        "artist": "",
        "file": "audio/modern/[Michael Wyckoff] Michael Wyckoff - House of Monogon (Boneworks OST) (lyq_sEF8iCQ).mp3",
        "duration": null
      },
      {
        "title": "[Michael Wyckoff] Michael Wyckoff, Kalya Ramu & Nathan Ford Don't Fence Me In (Bonelab OST) (3abZal0fXCU)",
        "artist": "",
        "file": "audio/modern/[Michael Wyckoff] Michael Wyckoff, Kalya Ramu & Nathan Ford - Don't Fence Me In (Bonelab OST) (3abZal0fXCU).mp3",
        "duration": null
      },
      {
        "title": "[The Newton Brothers] Five Nights at Freddy's (EuuZg3TUOlU)",
        "artist": "",
        "file": "audio/modern/[The Newton Brothers] Five Nights at Freddy's (EuuZg3TUOlU).mp3",
        "duration": null
      },
      {
        "title": "[The Newton Brothers] My Grandfather's Clock (3TarZctjb5k)",
        "artist": "",
        "file": "audio/modern/[The Newton Brothers] My Grandfather's Clock (3TarZctjb5k).mp3",
        "duration": null
      },
      {
        "title": "[Thomas The Cat] Jojo's Bizarre Adventure Diamond is Unbreakable Opening 1 (Creditless) ｜｜ [HD] (20m00ohYASw)",
        "artist": "",
        "file": "audio/modern/[Thomas The Cat] Jojo's Bizarre Adventure Diamond is Unbreakable - Opening 1 (Creditless) ｜｜ [HD] (20m00ohYASw).mp3",
        "duration": null
      },
      {
        "title": "[TryHardNinja] (SFM) ENNARD SONG ˝Nightmare by Design˝ by TryHardNinja & Hipsta Clique (ad8MDKgQNA8)",
        "artist": "",
        "file": "audio/modern/[TryHardNinja] (SFM) ENNARD SONG ˝Nightmare by Design˝ by TryHardNinja & Hipsta Clique (ad8MDKgQNA8).mp3",
        "duration": null
      },
      {
        "title": "[Yugo Kanno Topic] Theme of Stone Ocean (gFAk1RgX2Zo)",
        "artist": "",
        "file": "audio/modern/[Yugo Kanno - Topic] Theme of Stone Ocean (gFAk1RgX2Zo).mp3",
        "duration": null
      },
      {
        "title": "Stroheim Theme but it's EPIC VERSION (Propaganda) [bi3lqLq2uCw]",
        "artist": "",
        "file": "audio/modern/Stroheim Theme but it's EPIC VERSION (Propaganda) [bi3lqLq2uCw].mp3",
        "duration": null
      }
    ]
  },
  "atomic": {
    "name": "Atomic",
    "icon": "☢",
    "description": "Cold war tension and nuclear age",
    "songs": [
      {
        "title": "“Cold War” Call of Duty®: Black Ops Cold War Main Theme [9FvtJDPJCe8]",
        "artist": "",
        "file": "audio/atomic/“Cold War” - Call of Duty®: Black Ops Cold War Main Theme [9FvtJDPJCe8].mp3",
        "duration": null
      },
      {
        "title": "[Milan Records USA] KOMM, SUSSER TOD M 10 Director's Edit Version ｜ Evangelion Finally (hoKluzn07eQ)",
        "artist": "",
        "file": "audio/atomic/[Milan Records USA] KOMM, SUSSER TOD M-10 Director's Edit Version ｜ Evangelion Finally (hoKluzn07eQ).mp3",
        "duration": null
      },
      {
        "title": "[Mouks] FNAF Secret of the Mimic OST： A Poisonous Kiss (Credits) (YU5WuyQeEuw)",
        "artist": "",
        "file": "audio/atomic/[Mouks] FNAF Secret of the Mimic OST： A Poisonous Kiss (Credits) (YU5WuyQeEuw).mp3",
        "duration": null
      },
      {
        "title": "[Mouks] FNAF Secret of the Mimic OST： Dreamland Stardust (Warehouse Speakers) (tFCImgzHwG8)",
        "artist": "",
        "file": "audio/atomic/[Mouks] FNAF Secret of the Mimic OST： Dreamland Stardust (Warehouse Speakers) (tFCImgzHwG8).mp3",
        "duration": null
      },
      {
        "title": "Call of Duty Black Ops Cold War Zombies Reveal Trailer Song \"Tainted Love\" [hG0NVyqFm5o]",
        "artist": "",
        "file": "audio/atomic/Call of Duty Black Ops Cold War - Zombies Reveal Trailer Song  \"Tainted Love\" [hG0NVyqFm5o].mp3",
        "duration": null
      },
      {
        "title": "Comrades in Arms [GH5PYErxqNk]",
        "artist": "",
        "file": "audio/atomic/Comrades in Arms [GH5PYErxqNk].mp3",
        "duration": null
      },
      {
        "title": "Creedence Clearwater Revival Run Through The Jungle | Call of Duty: Black Ops Cold War OST [g sWLiWvYDc]",
        "artist": "",
        "file": "audio/atomic/Creedence Clearwater Revival - Run Through The Jungle | Call of Duty: Black Ops Cold War OST [g-sWLiWvYDc].mp3",
        "duration": null
      },
      {
        "title": "Devilman Crybaby Smells like Blood [HQ] [lFEw8iGAFoU]",
        "artist": "",
        "file": "audio/atomic/Devilman Crybaby - Smells like Blood [HQ] [lFEw8iGAFoU].mp3",
        "duration": null
      },
      {
        "title": "Puff Daddy & Lil Kim Notorious B.I.G (Call of Duty Black Ops Cold War Multiplayer Reveal Song) [hN69QFTEA64]",
        "artist": "",
        "file": "audio/atomic/Puff Daddy & Lil Kim - Notorious B.I.G (Call of Duty Black Ops Cold War Multiplayer Reveal Song) [hN69QFTEA64].mp3",
        "duration": null
      },
      {
        "title": "Rising Tide [Jd STVd5LUg]",
        "artist": "",
        "file": "audio/atomic/Rising Tide [Jd_STVd5LUg].mp3",
        "duration": null
      },
      {
        "title": "The Notorious B.I.G. Notorious B.I.G. | Call of Duty: Black Ops Cold War OST [VPtebmnq OQ]",
        "artist": "",
        "file": "audio/atomic/The Notorious B.I.G. - Notorious B.I.G. | Call of Duty: Black Ops Cold War OST [VPtebmnq-OQ].mp3",
        "duration": null
      }
    ]
  },
  "information": {
    "name": "Information",
    "icon": "💻",
    "description": "Digital age, peak energy, late-game vibes",
    "songs": [
      {
        "title": "[Crunchyroll] Attack on Titan Final Season Opening 2 ｜ The Rumbling (EtjQVqXUPHo)",
        "artist": "",
        "file": "audio/information/[Crunchyroll] Attack on Titan Final Season - Opening 2 ｜ The Rumbling (EtjQVqXUPHo).mp3",
        "duration": null
      },
      {
        "title": "[Crunchyroll] DAN DA DAN Opening ｜ Otonoke by Creepy Nuts (a4na2opArGY)",
        "artist": "",
        "file": "audio/information/[Crunchyroll] DAN DA DAN Opening ｜ Otonoke by Creepy Nuts (a4na2opArGY).mp3",
        "duration": null
      },
      {
        "title": "[CyberCodeFX] JoJo's Bizarre Adventure ｜ Opening 6 chase ｜ 4K Creditless HD (aCmJCQfINVU)",
        "artist": "",
        "file": "audio/information/[CyberCodeFX] JoJo's Bizarre Adventure ｜ Opening 6 - chase ｜ 4K Creditless HD (aCmJCQfINVU).mp3",
        "duration": null
      },
      {
        "title": "[CyberCodeFX] JoJo's Bizarre Adventure ｜ Opening 7 Great Days ｜ 4K Creditless HD (mU3vgXUKeFM)",
        "artist": "",
        "file": "audio/information/[CyberCodeFX] JoJo's Bizarre Adventure ｜ Opening 7 - Great Days ｜ 4K Creditless HD (mU3vgXUKeFM).mp3",
        "duration": null
      },
      {
        "title": "[FalKKonE] Doki Doki Literature Club! Your Reality (feat. Rena) 【Intense Symphonic Metal Cover】 (pzMmSIZixgE)",
        "artist": "",
        "file": "audio/information/[FalKKonE] Doki Doki Literature Club! - Your Reality (feat. Rena) 【Intense Symphonic Metal Cover】 (pzMmSIZixgE).mp3",
        "duration": null
      },
      {
        "title": "[Michael Wyckoff] Michael Wyckoff & Veronica Goudie Take A Ride (Bonelab OST) (Q UMzzPG9vg)",
        "artist": "",
        "file": "audio/information/[Michael Wyckoff] Michael Wyckoff & Veronica Goudie - Take A Ride (Bonelab OST) (Q-UMzzPG9vg).mp3",
        "duration": null
      },
      {
        "title": "[Nico Bellisario] JoJo ★ JOJOLION OP ★『GO BEYOND !』 Original JoJo's Bizarre Adventure Part 8【ジョジョの奇妙な冒険】 ジョジョリオン (g7TcFvORooU)",
        "artist": "",
        "file": "audio/information/[Nico Bellisario] JoJo ★ JOJOLION OP ★『GO BEYOND !』- Original - JoJo's Bizarre Adventure Part 8【ジョジョの奇妙な冒険】 ジョジョリオン (g7TcFvORooU).mp3",
        "duration": null
      },
      {
        "title": "[The Living Tombstone] Five Nights at Freddy's 1 Song The Living Tombstone (l18A5BOTlzE)",
        "artist": "",
        "file": "audio/information/[The Living Tombstone] Five Nights at Freddy's 1 Song - The Living Tombstone (l18A5BOTlzE).mp3",
        "duration": null
      },
      {
        "title": "[The Living Tombstone] Five Nights at Freddy's 2 Song The Living Tombstone (FNAF2) (gk aCL6eyGc)",
        "artist": "",
        "file": "audio/information/[The Living Tombstone] Five Nights at Freddy's 2 Song - The Living Tombstone (FNAF2) (gk-aCL6eyGc).mp3",
        "duration": null
      },
      {
        "title": "[The Living Tombstone] Five Nights at Freddy's 3 Song (Feat. EileMonty & Orko) Die In A Fire (FNAF3) Living Tombstone (AibtyCAhyQE)",
        "artist": "",
        "file": "audio/information/[The Living Tombstone] Five Nights at Freddy's 3 Song (Feat. EileMonty & Orko) - Die In A Fire (FNAF3)  - Living Tombstone (AibtyCAhyQE).mp3",
        "duration": null
      },
      {
        "title": "[The Living Tombstone] Five Nights at Freddy's 4 Song I Got No Time (FNAF4) The Living Tombstone (YREhVveHq9k)",
        "artist": "",
        "file": "audio/information/[The Living Tombstone] Five Nights at Freddy's 4 Song - I Got No Time (FNAF4) - The Living Tombstone (YREhVveHq9k).mp3",
        "duration": null
      },
      {
        "title": "[The Living Tombstone] Five Nights At Freddy's SB Song This Comes From Inside The Living Tombstone (X6ELpluyZyg)",
        "artist": "",
        "file": "audio/information/[The Living Tombstone] Five Nights At Freddy's SB Song - This Comes From Inside - The Living Tombstone (X6ELpluyZyg).mp3",
        "duration": null
      },
      {
        "title": "[The Living Tombstone] Five Nights at Freddys Sister Location Song I Can’t Fix You(FNAFSL) The Living Tombstone & Crusher P (kXMwZNRiPe0)",
        "artist": "",
        "file": "audio/information/[The Living Tombstone] Five Nights at Freddys Sister Location Song-I Can’t Fix You(FNAFSL)-The Living Tombstone & Crusher-P (kXMwZNRiPe0).mp3",
        "duration": null
      },
      {
        "title": "[ULTRAKILL] That one part from War Without Reason [dS mwjziWpI]",
        "artist": "",
        "file": "audio/information/[ULTRAKILL] That one part from War Without Reason [dS-mwjziWpI].mp3",
        "duration": null
      },
      {
        "title": "『転生したらスライムだった件』第4期オープニング映像 第2弾 [zvIS6EIkXx8]",
        "artist": "",
        "file": "audio/information/『転生したらスライムだった件』第4期オープニング映像 第2弾 [zvIS6EIkXx8].mp3",
        "duration": null
      },
      {
        "title": "Altars of Apostasy [m5ra w1xct8]",
        "artist": "",
        "file": "audio/information/Altars of Apostasy [m5ra-w1xct8].mp3",
        "duration": null
      },
      {
        "title": "Castle Vein [AX9pqyjYZBM]",
        "artist": "",
        "file": "audio/information/Castle Vein [AX9pqyjYZBM].mp3",
        "duration": null
      },
      {
        "title": "DOOM Eternal OST The Only Thing They Fear Is You (Extended Intro) [ekY09M48Jvs]",
        "artist": "",
        "file": "audio/information/DOOM Eternal OST - The Only Thing They Fear Is You (Extended Intro) [ekY09M48Jvs].mp3",
        "duration": null
      },
      {
        "title": "Doom OST At DOOM's Gate [HPZ5CxfuKqU]",
        "artist": "",
        "file": "audio/information/Doom OST - At DOOM's Gate [HPZ5CxfuKqU].mp3",
        "duration": null
      },
      {
        "title": "il vento d'oro [FPyIMtXsIcY]",
        "artist": "",
        "file": "audio/information/il vento d'oro [FPyIMtXsIcY].mp3",
        "duration": null
      },
      {
        "title": "Mick Gordon 02. Rip & Tear [zZMg9ryeWOw]",
        "artist": "",
        "file": "audio/information/Mick Gordon - 02. Rip & Tear [zZMg9ryeWOw].mp3",
        "duration": null
      },
      {
        "title": "Mick Gordon 11. BFG Division [QHRuTYtSbJQ]",
        "artist": "",
        "file": "audio/information/Mick Gordon - 11. BFG Division [QHRuTYtSbJQ].mp3",
        "duration": null
      },
      {
        "title": "Order [9E0xFvFCUTM]",
        "artist": "",
        "file": "audio/information/Order [9E0xFvFCUTM].mp3",
        "duration": null
      },
      {
        "title": "Recollect [UnhtcRJVLlo]",
        "artist": "",
        "file": "audio/information/Recollect [UnhtcRJVLlo].mp3",
        "duration": null
      },
      {
        "title": "スターダストクルセイダース [wtrFQLivuCg]",
        "artist": "",
        "file": "audio/information/スターダストクルセイダース [wtrFQLivuCg].mp3",
        "duration": null
      }
    ]
  }
};
