/**
 * generate-tracks.js
 * ------------------
 * Run this whenever you add OR remove songs.
 *
 * It completely rebuilds js/tracks-data.js from whatever is currently
 * inside the audio/<era>/ folders. That means:
 *   - new files appear automatically
 *   - deleted files are gone (no manual cleanup needed)
 *
 * Usage:
 *   node generate-tracks.js
 *
 * No extra packages required.
 * Filename → title (cleaned). Client-side reads real ID3 tags when playing.
 */

const fs = require("fs");
const path = require("path");

const AUDIO_DIR = path.join(__dirname, "audio");
const OUTPUT = path.join(__dirname, "js", "tracks-data.js");

// Must match the keys used in the player
const ERAS = {
  ancient:      { name: "Ancient",      icon: "🏛", description: "Mysterious, epic, foundational vibes" },
  classical:    { name: "Classical",    icon: "🏺", description: "Grandeur and rising empires" },
  medieval:     { name: "Medieval",     icon: "🏰", description: "Castles, faith, and steel" },
  renaissance:  { name: "Renaissance",  icon: "🎨", description: "Discovery and enlightenment" },
  industrial:   { name: "Industrial",   icon: "⚙", description: "Factories, steam, and progress" },
  modern:       { name: "Modern",       icon: "✈", description: "World wars to the jet age — high energy" },
  atomic:       { name: "Atomic",       icon: "☢", description: "Cold war tension and nuclear age" },
  information:  { name: "Information",  icon: "💻", description: "Digital age, peak energy, late-game vibes" },
};

const AUDIO_EXTS = new Set([".mp3", ".m4a", ".ogg", ".wav", ".flac"]);

function cleanTitle(filename) {
  // Remove extension and turn common separators into spaces
  return filename
    .replace(/\.[^/.]+$/, "")
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function scanEra(eraKey) {
  const folder = path.join(AUDIO_DIR, eraKey);
  if (!fs.existsSync(folder)) {
    console.log(`  ⚠  No folder: audio/${eraKey}/`);
    return [];
  }

  const files = fs.readdirSync(folder)
    .filter(f => AUDIO_EXTS.has(path.extname(f).toLowerCase()))
    .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }));

  return files.map(file => ({
    title: cleanTitle(file),
    artist: "",               // filled later by client-side ID3 if available
    file: `audio/${eraKey}/${file}`,
    duration: null            // filled by <audio> element when loaded
  }));
}

function main() {
  console.log("Scanning audio folders (full rebuild)...\n");

  const tracks = {};

  for (const [key, meta] of Object.entries(ERAS)) {
    const songs = scanEra(key);
    tracks[key] = {
      name: meta.name,
      icon: meta.icon,
      description: meta.description,
      songs
    };
    console.log(`  ${meta.icon}  ${meta.name.padEnd(12)} → ${songs.length} track(s)`);
  }

  const output = `/**
 * AUTO-GENERATED by generate-tracks.js
 * Do not edit by hand — just re-run the script after adding/removing files.
 * Generated: ${new Date().toISOString()}
 *
 * This file is completely rewritten every run, so deleted songs disappear automatically.
 */
window.TRACKS_DATA = ${JSON.stringify(tracks, null, 2)};
`;

  fs.writeFileSync(OUTPUT, output, "utf8");
  console.log(`\n✓ Wrote ${OUTPUT}`);
  console.log("Done. Refresh the page.\n");
}

main();